#!/bin/bash

SCRIPT=$(realpath ${0})
SCRIPT_PATH=$(dirname ${SCRIPT})
RUN_OPTIONS=

cd "${SCRIPT_PATH}"

if ! [[ -z ${NO_DEPS+x} ]] ; then
    RUN_OPTIONS="--no-deps"
fi

[ -d ~/.ssh ] || mkdir ~/.ssh && chmod 700 ~/.ssh
[ -d ~/.composer ] || mkdir ~/.composer

docker-compose run ${RUN_OPTIONS} --rm -e TARGET_UID="$(id -u)" php ${@:-bin/console}
