trainingPeriod1:
  startDate: '2024-11-01'
  endDate: '2025-04-01'
  trainingSeason: !php/enum App\Enum\TrainingSeasonEnum::WINTER
  trainingPlace: trainingPlace1

trainingPeriod2:
  startDate: '2025-04-02'
  endDate: '2025-11-01'
  trainingSeason: !php/enum App\Enum\TrainingSeasonEnum::SUMMER
  trainingPlace: trainingPlace2
